library:
  source-dirs: src
tests:
  plp-hs-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - plp-hs
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
  - transformers
  - containers
  - base >= 4.7 && < 5
  - parsec
name: plp-hs
version: 0.1.0.0
extra-source-files:
  - README.md
  - ChangeLog.md
author: Author name here
github: githubuser/plp-hs
license: BSD3
executables:
  plp-hs-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - plp-hs
description: Please see the README on GitHub at <https://github.com/githubuser/plp-hs#readme>
